export const creativeReasons = [
  // Existing & New Additions
  "My aura is out for cleaning.",
  "I'm allergic to that particular vibe.",
  "My shadow needs a break.",
  "That's outside my emotional budget.",
  "I'm currently vibrating at the wrong frequency.",
  "My comforter has taken me hostage.",
  "I'm on a strict regimen of 'no'.",
  "The toaster is giving me the silent treatment.",
  "My brain's firewall blocked that request.",
  "I have a meeting with my bed I can't postpone.",
  "My introversion is flaring up.",
  "I'm pursuing a Ph.D. in napping.",
  "I'm converting oxygen to sarcasm; it requires focus.",
  "My social battery is at 1%.",
  "The dust bunnies are unionizing. I'm mediating.",
  "I have to go water my fake plants.",
  "My timeline is undergoing unscheduled maintenance.",
  "My spoons are on strike.",
  "I have an update pending... for my soul.",
  "My pet void needs feeding.",
  "The couch requires my full attention.",
  "I'm in a committed relationship with my WiFi.",
  "My plants have performance anxiety.",
  "My horoscope advised against shenanigans.",
  "I'm emotionally unavailable for that.",
  "My skeleton is feeling boneless today.",
  "I'm not in my Roomba's approved safe zone.",
  "The ceiling fan has some interesting theories.",
  "I'm practicing the art of being a hermit.",
  "My guardian demon said it's a trap.",
  "I'm currently off-brand.",
  "The laundry pile has become sentient.",
  "My existential dread has a plus-one.",
  "I have to alphabetize my regrets.",
  "My inner child is grounded.",
  "I'm on do-not-disturb mode for my soul.",
  "My Netflix queue is judging me.",
  "I'm holding a seminar for my houseplants.",
  "My Bluetooth is feeling antisocial.",
  "I'm in energy-saving mode.",
  "The cat has my emotional support animal today.",
  "I'm observing a moment of silence... all day.",
  "My life is currently in beta testing.",
  "I'm in a staring contest with my reflection.",
  "My coffee maker is staging a protest.",
  "I've scheduled a self-care filibuster.",
  "My dog hid my motivation.",
  "I'm ghosting reality for a bit.",
  "My anxiety needs to be walked.",
  "The Wi-Fi password changed itself to 'no'.",
  "I'm recalibrating my personality.",
  "My pet rock is shedding.",
  "The floor is lava. All floors. Everywhere.",
  "I'm reverse-photosynthesizing today.",
  "My salt lamp is feeling dim.",
  "I have a previous engagement with my imagination.",
  "I'm running a diagnostic on my life choices.",
  "My motivation is stuck in traffic.",
  "I'm busy disappointing my ancestors.",
  "My phone is on 100%, can't risk it.",
  "I'm not subscribed to that particular drama.",
  "My spirit animal is hibernating.",
  "I'm fermenting. It's a delicate process.",
  "The remote control has gone rogue.",
  "I'm experiencing a high volume of 'me'.",
  "My personal weather forecast is indoorsy.",
  "I'm curating a collection of naps.",
  "That event doesn't support my current OS.",
  "I'm in a feud with my own ambition.",
  "My hair has decided against it.",
  "I have to floss my memories.",
  "The moon is in a weird mood.",
  "I'm on a quest for a misplaced thought.",
  "My cheese is aging and needs supervision.",
  "I'm marinating in a state of unbothered.",
  "My front door is being emotionally distant.",
  "I have to attend the funeral of my motivation.",
  "I'm practicing my right to remain silent.",
  "The chair has accepted me as its leader.",
  "I'm currently at capacity for shenanigans.",
  "My sense of direction has clocked out.",
  "I'm knitting a sweater for my ego.",
  "My algorithm forbids it.",
  "I'm teaching my goldfish how to yawn.",
  "That's not in my emotional wheelhouse.",
  "My attention span is on backorder.",
  "The fridge light and I have beef.",
  "I'm building a pillow fort. For security reasons.",
  "I'm having my aura professionally fluffed.",
  "My shoes are not speaking to each other.",
  "I'm too busy overthinking a past conversation.",
  "My playlist needs me.",
  "I'm on a digital detox from reality.",
  "My tea needs to be emotionally supported while it steeps.",
  "I have an appointment with a good book.",
  "The squirrels are mocking me again.",
  "I'm trying to un-learn my own name.",
  "My chakras are misaligned.",
  "I'm waiting for a sign. This is not it.",
  "My brain has too many tabs open.",
  "I'm being audited by the karma police.",
  "My comfort zone is currently a gated community.",
  "I've got a hot date with a bowl of cereal.",
  "I'm trying to set a new world record for blinking.",
  "My thoughts are not fit for public consumption.",
  "The cat changed the password to the front door.",
  "I'm not in the mood to pretend to be a functional human.",
  "I'm having an out-of-money experience.",
  "I'm in the middle of a silent disco for one.",
  "My mitochondria are tired.",
  "I'm busy not making plans.",
  "That sounds suspiciously like effort.",
  "I'm decluttering my personality.",
  "The universe and I are having a disagreement.",
  "I have to put my thoughts in alphabetical order.",
  "My future self advised against it.",
  "I'm trying to communicate with a spider.",
  "My desire to participate has flatlined.",
  "I'm currently in airplane mode.",
  "My imaginary friend is sick.",
  "I'm testing the limits of my pajamas.",
  "My calendar is allergic to that day.",
  "I'm on a pilgrimage to the refrigerator.",
  "I'm proofreading the dictionary.",
  "My past self made other plans for me.",
  "The static electricity in my house is hostile.",
  "I'm having a staring contest with a houseplant.",
  "I'm busy with a non-disclosure agreement with myself.",
  "My will to live is recharging.",
  "I'm exploring the uncharted territories of my couch cushions.",
  "I'm undergoing a software update.",
  "My sense of humor is under maintenance.",
  "I'm solving the mystery of the missing sock.",
  "My procrastination is finally paying off.",
  "I'm not taking calls from reality today.",
  "My enthusiasm is on a coffee break.",
  "I'm busy being a cautionary tale.",
  "I'm conducting a very important lint collection audit.",
  "My ability to 'people' has expired.",
  "I'm in a long-term relationship with my bed.",
  "The dog ate my social skills.",
  "I'm reorganizing my priorities, and that ain't one.",
  "I'm emotionally invested in this bag of chips.",
  "My keys are playing hide and seek.",
  "I'm in the witness protection program from my responsibilities.",
  "My get-up-and-go has got up and gone.",
  "I'm currently using my right to be boring.",
  "I've been advised by my council of cats to stay home.",
  "I'm holding a press conference for my insecurities.",
  "My sanity is a subscription service, and I missed a payment.",
  "I'm waiting for my clone to get back to me.",
  "My GPS says 'Emotionally Unavailable'.",
  "I'm in a thumb war with my conscience.",
  "The plot of my life is currently thickening at home.",
  "I have to count all the dust particles in this sunbeam.",
  "My day is exclusively sponsored by 'nope'.",
  "I'm color-coding my anxieties.",
  "I'm in a philosophical debate with my reflection.",
  "My brain is buffering.",
  "I'm on a need-to-not-know basis.",
  "I'm trying to levitate. It's not going well.",
  "My circadian rhythm is giving me the silent treatment.",
  "I'm in my cocoon phase.",
  "My socks are in charge today, and they say no.",
  "I'm experiencing user-end error.",
  "My patience is still rendering.",
  "I'm in a complicated relationship with 'outside'.",
  "I'm trying to teach my cat about capitalism.",
  "The gravity in my house is stronger today.",
  "I'm having my portrait painted by a ghost.",
  "My ambition and I are on a break.",
  "I have to manually restart my personality.",
  "I'm practicing my acceptance speech for an award I'll never get.",
  "My tolerance for nonsense is at an all-time low.",
  "I'm in a turf war with a local pigeon.",
  "My sleep schedule is laughing at me.",
  "I'm trying to remember what I forgot.",
  "My internal monologue is too loud today.",
  "I'm on a low-carb diet for drama.",
  "I'm re-reading the terms and conditions of my existence.",
  "My dog thinks I'm an emotional support human.",
  "I'm currently experiencing life in 'story mode'.",
  "My common sense is on vacation.",
  "I'm filing an extension on my adulthood.",
  "My motivation has been successfully quarantined.",
  "I'm at a high risk of becoming comfortable.",
  "My enthusiasm has been recalled by the manufacturer.",
  "I'm conducting a seance to find a missing Tupperware lid.",
  "My phone's horoscope said 'stay in'.",
  "I'm boycotting pants.",
  "My shadow is on strike for better lighting.",
  "I'm in a creativity coma.",
  "I'm translating the WiFi signal into Latin.",
  "My pet peeves are having a family reunion.",
  "I'm in the process of becoming a blanket burrito.",
  "My car is pretending to be a lawn ornament.",
  "I'm trying to un-send an email from 2012.",
  "My brain has been replaced by a dial-up modem.",
  "I'm having a bad hair century.",
  "My sense of wonder has wandered off.",
  "I'm supervising the ice cubes.",
  "My snack supply is critically low.",
  "I'm not compatible with that version of reality.",
  "My self-control is out of the office.",
  "I'm in a civil dispute with a cloud.",
  "My life is not taking new friend applications at this time.",
  "I'm being haunted by my to-do list.",
  "I have a non-refundable ticket to my couch.",
  "My therapist said I need more 'me' time. This is it.",
  "I'm busy not being busy.",
  "My capacity for human interaction is full.",
  "I'm testing my smoke alarm with burnt toast.",
  "My inner peace is on back order.",
  "I'm in a staring contest with the abyss.",
  "My brain cell is on its lunch break.",
  "I'm observing the migration patterns of my dust bunnies.",
  "My apathy is at its peak performance.",
  "I'm currently off the grid. The social grid.",
  "I'm trying to remember the plot of my own life.",
  "My wallet is in self-isolation.",
  "I'm under new management. Myself.",
  "My personal bubble has been upgraded to a fortress.",
  "I'm in a delicate negotiation with a spider.",
  "My plans have been canceled by popular demand (mine).",
  "I'm on a cleanse from other people's energy.",
  "My dog is having an existential crisis.",
  "I'm in the middle of a very slow-motion dance party.",
  "My enthusiasm has been furloughed.",
  "I'm trying to figure out what the microwave is thinking.",
  "My body has decided it's a plant today.",
  "I'm not currently accepting reality's friend request.",
  "My attention span has left the chat.",
  "I'm memorizing the patterns on my ceiling.",
  "My vibe is currently 'dial-up internet'.",
  "I'm in a witness protection program from my own life.",
  "My need for validation is offline.",
  "I'm teaching myself to be ambidextrous with my laziness.",
  "My motivation has ghosted me.",
  "I'm busy calculating the meaning of life on a napkin.",
  "My pet cheese is having a birthday party.",
  "I'm on an audio-book adventure.",
  "My chill has been permanently lost.",
  "I'm busy being a figment of my own imagination.",
  "I'm performing a citizen's arrest on my ambitions.",
  "My dog's horoscope said we should stay in.",
  "I'm running low on the appropriate facial expressions.",
  "I'm currently at a S P A C E conference.",
  "My spirit has been decommissioned for the day.",
  "I'm in a passive-aggressive relationship with my alarm clock.",
  "I have an important meeting with a snack.",
  "My level of preparedness is zero.",
  "I'm busy with my anti-social agenda.",
  "My brain is not accepting new information at this time.",
  "I'm in a long-distance relationship with my motivation.",
  "My energy levels are a myth.",
  "I'm practicing the ancient art of doing nothing.",
  "My to-do list has filed for divorce.",
  "I'm too sober for that.",
  "My life's narrative arc is currently flat.",
  "I'm on a watchlist. My cat's.",
  "My operating system is not supported.",
  "I'm beta-testing a new personality.",
  "My sense of urgency is on sabbatical.",
  "I'm in a standoff with a pile of dishes.",
  "My phone is having a personal day.",
  "I'm not in your Wi-Fi range.",
  "My pet dust bunny is sick.",
  "I'm currently set to 'private'.",
  "My shoes don't feel like going out.",
  "I'm busy fighting my inner demons. And losing.",
  "My productivity has been abducted by aliens.",
  "I'm having my aura re-textured.",
  "My brain is closed for renovations.",
  "I'm trying to get my pet rock to do tricks.",
  "My social skills are in the wash.",
  "I'm in a quiet feud with the concept of time.",
  "My give-a-damn is broken.",
  "I'm conducting important research on my ceiling.",
  "My cloud storage for memories is full.",
  "I'm in a creative dispute with reality.",
  "My soul is not dressed for that.",
  "I'm having a private party with my anxieties.",
  "My motivation has been set to 'read only'.",
  "I'm observing a national holiday for introverts.",
  "My personal assistant (my cat) said no.",
  "I'm currently experiencing planned obsolescence.",
  "My vibe curator has the day off.",
  "I'm busy not being there.",
  "My capacity for that is zero.",
  "I'm in a witness protection program for my sanity.",
  "My enthusiasm got lost in the mail.",
  "I'm having a moment of Zen. Or ten.",
  "My DNA said no.",
  "I'm in a simulation, and it's lagging.",
  "My inner sloth has been awakened.",
  "I'm busy overthinking something trivial.",
  "My car is not in the mood.",
  "I'm on an emotional rollercoaster that's stuck.",
  "My sarcasm requires a recharge.",
  "I'm holding auditions for my new personality.",
  "My phone and I are in a fight.",
  "I'm not emotionally equipped for that location.",
  "My dog is my alibi.",
  "I'm having a bad idea and I need to see it through.",
  "My personal space is having a personal day.",
  "I'm in a committed relationship with 'maybe later'.",
  "My brain has been recalled due to a manufacturing defect.",
  "I'm in the process of becoming one with my furniture.",
  "My apathy is a renewable resource.",
  "I'm too busy managing my imaginary empire.",
  "My existential crisis is an all-day event.",
  "I'm on a journey to the center of my couch.",
  "My sense of adventure is being rebooted.",
  "I'm having a deep conversation with my leftovers.",
  "My good intentions have been delayed.",
  "I'm not on the guest list for reality tonight.",
  "My future self is disappointed in me already.",
  "I'm in a staring contest with my future.",
  "My motivation has been placed on the no-fly list.",
  "I'm currently experiencing technical difficulties.",
  "My inner gremlin needs to be appeased.",
  "I'm busy being a mystery to myself.",
  "My sense of humor is on backorder.",
  "I'm not in a 'putting on shoes' state of mind.",
  "My pet peeve is having a tantrum.",
  "I'm in the process of forgetting your request.",
  "My life is currently rated E for Everyone staying home.",
  "I'm busy being an urban legend.",
  "My social skills have been updated to 'not responding'.",
  "I'm having a strategic nap.",
  "My dog gave me side-eye, so I can't.",
  "I'm on a strict diet of comfort and quiet.",
  "My level of interest has been declared a natural disaster.",
  "I'm busy.",
];