export const lazyReasons = [
  // Original Reasons
  "I'm in a committed relationship with my couch.",
  "I'm busy washing my hair for the next 6 months.",
  "I promised my houseplants I'd stay home.",
  "I'd love to, but I'm practicing the ancient art of doing nothing.",
  "My phone battery is at 99% - too risky to leave the house.",
  "I'm busy reorganizing my sock drawer by color and emotional attachment.",
  "I promised my Netflix I wouldn't cheat on it.",
  "Sorry, I'm fully booked with important cat videos.",
  "I'm saving my energy for more important rejections.",
  "My social battery died and the charger is broken.",
  "I'm allergic to plans that require pants.",
  "Sorry, I'm in a serious relationship with procrastination.",
  "My bed and I have an exclusive contract.",
  "I'm allergic to activities that require effort.",
  "Sorry, I'm practicing the ancient art of hermit-ing.",
  "My motivation took a vacation and didn't leave a forwarding address.",
  "I'm on a strict diet of avoiding responsibilities.",
  "I'm busy being professionally antisocial.",
  "I'm on a strict no-fun diet prescribed by my sanity.",
  "Sorry, I'm busy avoiding people who make plans.",

  // New Additions
  "My blanket has separation anxiety and I can't leave it.",
  "I'm in energy-saving mode.",
  "That sounds suspiciously like effort.",
  "I have a previous engagement with a nap.",
  "My get-up-and-go has got up and gone.",
  "I'm in my cocooning phase.",
  "My pajamas and I have a good thing going on, I don't want to ruin it.",
  "I'm conducting important research on the structural integrity of my mattress.",
  "My comfort zone is my only zone today.",
  "I have to stay home to make sure my snacks don't get lonely.",
  "That requires a level of 'peopling' I can't afford right now.",
  "I'm philosophically opposed to productivity today.",
  "My couch is my co-pilot, and we're not flying anywhere.",
  "I'm building a pillow fort and I'm the sole occupant.",
  "I'm on a quest to find the end of the internet.",
  "My motivation has been placed on the no-fly list.",
  "I'm a professional relaxer, and I'm on the clock.",
  "My inertia is particularly strong today.",
  "I'm observing a personal holiday called 'Me Day'.",
  "I'm too invested in this show to move.",
  "My body has decided to be a plant for the day.",
  "I'm not leaving the house until my phone is at 101%.",
  "I'm emotionally unavailable for activities.",
  "My ability to even has reached its limit.",
  "I have a very demanding schedule of doing absolutely nothing.",
  "I'm in a long-term relationship with my streaming service.",
  "My doctor prescribed a heavy dose of 'chill'.",
  "That sounds like a problem for 'Future Me'.",
  "I'm exploring the great indoors.",
  "My sloth spirit animal has been activated.",
  "I'm on a low-energy diet.",
  "I'm not accepting invitations, only deliveries.",
  "My enthusiasm is on backorder.",
  "I'm in the middle of a very important staring contest with the ceiling.",
  "I'm conserving my awesomeness.",
  "I've got a hot date with a good book and a cup of tea.",
  "My capacity for leaving the house has been maxed out for the month.",
  "I'm in a committed throuple with Ben & Jerry.",
  "My social meter is on 'E' and the nearest charging station is my bed.",
  "I'm boycotting responsibility.",
  "I'm trying to set a new personal record for consecutive hours on the couch.",
  "My laziness is a renewable resource I'm currently renewing.",
  "I'm holding my remote control for emotional support.",
  "My ambition is sleeping in today.",
  "I'm adhering to a strict 'no shoes, no leaving' policy.",
  "I'm too cozy to function.",
  "My brain is in airplane mode.",
  "I'm majoring in procrastination with a minor in napping.",
  "I have a responsibility to my comfort that I take very seriously.",
  "I'm not feeling very 'adult' today.",
  "My to-do list consists of 'breathe' and 'exist'. I'm on task.",
  "I'm on a journey to the center of my couch.",
  "My calendar is open for naps and snacks only.",
  "I'm currently logged off from life.",
  "I'm having a passionate love affair with my pillow.",
  "I've decided to opt out of today.",
  "My level of motivation is currently 'zero'.",
  "I'm in a deep, philosophical discussion with my cat about the merits of sleep.",
  "I'm practicing my stillness. It's an art form.",
  "The gravity is stronger in my house today.",
  "I'm under strict orders from myself to relax.",
  "My day is exclusively sponsored by the letter 'Zzzzz'.",
  "I have a very important appointment with my refrigerator.",
  "I'm experiencing a severe case of 'don't wanna'.",
  "My body and my bed are in a magnetic relationship.",
  "I'm off-duty from being a functional human.",
  "I'm on a staycation. In my living room.",
  "My spirit of adventure has retired.",
  "I'm in a standoff with my responsibilities, and I plan to win.",
  "My day is a 'no bones' day.",
  "I'm curating a playlist for my next nap.",
  "My social skills are recharging. It takes a while.",
  "I'm not taking calls from reality today.",
  "I have a backlog of relaxation I need to get through.",
  "My enthusiasm has been successfully quarantined.",
  "I am one with the furniture now.",
  "My daily agenda is 'pending'.",
  "I'm in my natural habitat: under a blanket.",
  "I'm waiting for motivation to strike. It hasn't.",
  "My only plan is to have no plans.",
  "I'm observing the sacred tradition of the lazy Sunday... on a Tuesday.",
  "I've achieved peak comfort and cannot be moved.",
  "I'm on an energy-saving quest.",
  "My desire to function is at an all-time low.",
  "I'm too busy doing me, which is doing nothing.",
  "I'm the CEO of chilling out.",
  "My plans for the day are horizontal.",
  "I'm running on fumes, and the fumes are lazy.",
  "My body has voted to veto that activity.",
  "I'm taking a personal day from the human race.",
  "I'm in a deep state of pre-nap.",
  "My will to move is currently out of service.",
];