export const professionalReasons = [
  // Original Reasons (duplicate removed)
  "I have a prior commitment that cannot be rescheduled.",
  "Unfortunately, I'm not available during that timeframe.",
  "I have a conflict in my calendar.",
  "I'm currently at capacity with other priorities.",
  "That doesn't align with my current objectives.",
  "I'm focusing my efforts on other initiatives.",
  "I'm not able to take on additional commitments at this time.",
  "That falls outside my area of expertise.",
  "I have resource constraints that prevent my participation.",
  "I'm already committed to other projects during that period.",
  "That doesn't fit with my current strategic priorities.",
  "I have a bandwidth limitation at the moment.",
  "Unfortunately, that's not feasible given my current workload.",
  "I need to decline due to competing priorities.",

  // New Additions
  "Thank you for the opportunity, but I am unable to commit at this time.",
  "I don't have the bandwidth to give this the attention it deserves.",
  "My current project load doesn't allow for any additional tasks.",
  "To ensure the quality of my current work, I must decline additional responsibilities.",
  "This falls outside the scope of my current role's objectives.",
  "My schedule is fully allocated for the foreseeable future.",
  "I need to prioritize my existing deliverables.",
  "This doesn't align with my team's current roadmap.",
  "I'm afraid I have a non-movable appointment at that time.",
  "I must respectfully decline in order to meet my existing deadlines.",
  "While I appreciate you thinking of me, my focus must remain on my primary responsibilities.",
  "I am not the subject matter expert on this topic.",
  "I believe another team member with expertise in [Area] would be a better fit.",
  "My calendar is locked for that period due to critical project work.",
  "I'm in the midst of a high-priority task that requires my full attention.",
  "I'm unable to contribute effectively with my current resource allocation.",
  "The timing for this isn't right; perhaps we can connect next quarter.",
  "I've been tasked with other projects that take precedence.",
  "Due to a prior engagement, I won't be able to participate.",
  "I need to keep my schedule clear to focus on my core functions.",
  "My involvement would be redundant as the team is already well-supported in this area.",
  "I am unable to take on any new projects until the next fiscal period.",
  "This requires a skill set that I am still developing.",
  "I'm heading into a critical delivery phase and can't be distracted.",
  "While I can't commit, I'd be interested in reviewing the meeting notes afterward.",
  "I will be out of office on pre-scheduled leave during that time.",
  "This request is not in alignment with my quarterly goals.",
  "I'm currently dedicated to a long-term project and cannot deviate.",
  "I am unable to accept, but I can recommend someone who might be available.",
  "My team's resources are fully committed to other objectives.",
  "That timeline is too aggressive given my current commitments.",
  "I must pass on this opportunity to focus on internal team priorities.",
  "I'm afraid my hands are tied with another deadline-sensitive project.",
  "I won't be able to provide the value you're looking for on this particular subject.",
  "I have a recurring meeting at that time that takes precedence.",
  "My role does not have the authority or scope to handle this.",
  "I'm trying to reduce my meeting load to improve focus on key deliverables.",
  "I have to bow out as my focus is on completing my current assignments.",
  "Let's touch base in a few weeks when my schedule has cleared up.",
  "I'm currently working on a time-sensitive issue.",
  "I'm not the best point of contact for this. I suggest reaching out to [Name/Department].",
  "I have a hard deadline that I cannot shift.",
  "My focus for this week is strictly on [Project Name].",
  "I need to keep my workload manageable to avoid burnout.",
  "I am protecting my schedule to focus on deep work.",
  "Unfortunately, I have another urgent matter to attend to.",
  "I have to decline as this conflicts with a client commitment.",
  "My current priorities were set by management and I'm not at liberty to change them.",
  "I'd be doing the project a disservice by joining with my current lack of availability.",
  "I have already allocated my time for this week and cannot make adjustments.",
];