export const relatedReasons = [
  // Original Reasons
  "My social battery died and the charger is broken.",
  "I'm on a strict diet of avoiding responsibilities.",
  "My anxiety has already RSVPed as a hard no.",
  "My stress levels are already at maximum capacity.",
  "I'm busy being professionally antisocial.",
  "My bank account and I aren't speaking right now.",
  "My common sense is telling me this is a trap.",
  "I'd love to, but I'm busy pretending to be a functional adult.",
  "My morning coffee hasn't given me permission yet.",
  "I'm allergic to leaving my comfort zone.",
  "Sorry, I'm allergic to social obligations.",
  "My therapist said I need to practice saying no more often.",
  "I'm saving my energy for more important rejections.",
  "My motivation took a vacation and didn't leave a forwarding address.",
  "I'm on a strict no-fun diet prescribed by my sanity.",
  "My inner child is having a tantrum about it.",
  "I'd rather explain social media to a caveman.",
  "I'd rather fold a fitted sheet blindfolded.",
  "I'd rather explain TikTok to my grandmother.",
  "Sorry, I'm busy disappointing my parents in other ways.",

  // New Additions
  "My emotional bandwidth is currently maxed out.",
  "I'm not taking on new tasks until my brain's current tabs are closed.",
  "That sounds like a problem for a version of me that's more responsible.",
  "My 'give-a-damn' meter is broken.",
  "I'm currently retired from adulting.",
  "I have a scheduled overthinking session at that time.",
  "I'd rather step on a Lego, intentionally.",
  "My capacity for small talk is at an all-time low.",
  "I'm practicing the fine art of JOMO (Joy Of Missing Out).",
  "That's not in my emotional budget for the week.",
  "I'm on a cleanse from making good decisions.",
  "My serotonin is on backorder.",
  "I'd rather try to assemble IKEA furniture with no instructions.",
  "I have a previous engagement with my own existential dread.",
  "My desire to participate has been socially distanced.",
  "I'm in my villain era, and my first act is saying no.",
  "I'm too busy managing the chaos that is my life.",
  "My future self has already warned me against this.",
  "I'm exercising my right to be completely unavailable.",
  "My anxiety and I are a package deal, and it's not feeling it.",
  "I'd rather untangle a decade's worth of Christmas lights.",
  "My life is not accepting new side quests at the moment.",
  "I'm in a committed relationship with avoiding that.",
  "I have to stay home and overthink something I did in 2012.",
  "I'm fresh out of the mental energy required for that.",
  "My wallet has entered a state of hibernation.",
  "I'm honouring my commitment to myself to do less.",
  "I'd rather watch paint dry. In slow motion.",
  "I'm not leaving my house until it feels less 'outside' out there.",
  "My ability to pretend I'm interested has expired.",
  "I'm trying to lower my carbon footprint by not going anywhere.",
  "My personal weather forecast predicts a 100% chance of staying indoors.",
  "I'm not currently accepting applications for 'things to do'.",
  "I'd rather get stuck in an elevator with a non-stop loop of 'Baby Shark'.",
  "My horoscope said to avoid human interaction for best results.",
  "I'm in a fight with my alarm clock and I'm siding with my bed.",
  "My to-do list is already a novel; I can't add another chapter.",
  "I have a very important date with my streaming queue.",
  "My life's current plotline requires me to be at home.",
  "I'd rather listen to a 3-hour lecture on the history of beige paint.",
  "That requires a certain level of 'put-together' that I don't possess today.",
  "My brain is currently running on dial-up speed.",
  "I'm taking a mental health day from the entire world.",
  "I'm too busy trying to keep my houseplants alive (and failing).",
  "My tolerance for human folly is at a deficit.",
  "I'm busy with a non-disclosure agreement I made with my couch.",
  "I'd rather find a needle in a haystack. Blindfolded. In another country.",
  "I'm saving my social energy for emergencies only.",
  "My life has been set to 'do not disturb'.",
  "I'm trying to see how long I can go without making a decision.",
  "I'm not emotionally prepared to wear 'hard pants'.",
  "I have to finish a conversation I started in my head yesterday.",
  "My common sense has filed a restraining order against that idea.",
  "I'm currently at my people-ing limit for the month.",
  "I'd rather be a background character in someone else's life right now.",
  "I'm busy trying to become a better person, which ironically involves seeing fewer people.",
  "My financial advisor (a Magic 8-Ball) said 'Outlook not so good'.",
];