export const sarcasticReasons = [
  // Original Reasons (duplicate removed)
  "Nah, I'm allergic to that level of commitment.",
  "Sorry, my calendar is booked with absolutely nothing.",
  "I'd rather watch paint dry on a rainy Tuesday.",
  "That sounds like a problem for future me to decline.",
  "Sorry, I'm allergic to social obligations.",
  "My therapist said I need to practice saying no more often.",
  "I'm allergic to leaving my comfort zone.",
  "I'd love to, but I'm practicing selective hearing.",
  "Sorry, I'm busy disappointing my parents in other ways.",
  "I'd rather fold a fitted sheet blindfolded.",
  "I'd love to, but I'm busy pretending to be a functional adult.",
  "My stress levels are already at maximum capacity.",
  "I'd rather explain social media to a caveman.",
  "My common sense is telling me this is a trap.",
  "My morning coffee hasn't given me permission yet.",
  "Sorry, I'm busy avoiding people who make plans.",
  "My bank account and I aren't speaking right now.",
  "I'd rather explain TikTok to my grandmother.",
  "I'm in witness protection from social events.",

  // New Additions
  "Wow, that sounds... like something I'm definitely not doing.",
  "I'll be there in spirit, which means I'll be on my couch.",
  "Let me check my schedule. It appears to be laughing hysterically.",
  "I'm trying to care, but my apathy is just too powerful.",
  "I wish I could, but I really don't want to.",
  "That sounds like an awful lot of fun that I'm determined to miss.",
  "I'm terribly busy attending the grand opening of my refrigerator.",
  "You've mistaken me for someone who is both available and interested.",
  "My 'give-a-damn' is on backorder.",
  "Thank you for the opportunity to practice my 'no'.",
  "I'm on a very tight schedule of doing whatever I want, and that's not on it.",
  "I'm suffering from a severe case of 'can't-be-bothered'.",
  "Let me pencil that in for the 30th of Never.",
  "I'm holding out for a better offer. From my bed.",
  "My 'enthusiasm' processor appears to be offline.",
  "I'm currently trying to underachieve my potential.",
  "Oh, what a shame, I have a recurring appointment with not doing that.",
  "I have to go and not do that now.",
  "I'm being held hostage by my own laziness.",
  "That sounds like it has the potential to be a memory I'd rather not make.",
  "I'm trying to reduce my carbon footprint by staying put. Indefinitely.",
  "I'm afraid that conflicts with my scheduled session of staring at a wall.",
  "My horoscope said I should avoid making good decisions today.",
  "I've run the numbers, and the result is a resounding 'meh'.",
  "I'd love to, but my cat said no.",
  "I'm currently in a committed relationship with avoiding that.",
  "My doctor said I need to avoid situations that don't involve my sofa.",
  "I'm not saying I'm not going to do it, but I'm not not saying it either.",
  "I'm self-partnered, and my partner wants to stay in.",
  "Unfortunately, my desire to do that has not been activated.",
  "I'm going to have to pass, for reasons that are frankly none of your business.",
  "I'm busy charging my social battery, which is, of course, a lie.",
  "I'm in the middle of a very important... something else.",
  "That sounds like a task for someone with a better attitude than me.",
  "My dog seems to be having a crisis and needs me for moral support.",
  "I'm boycotting that particular activity on principle.",
  "My personal assistant (my brain) has declined on my behalf.",
  "I'd rather perform a self-root-canal.",
  "I'm too busy making poor life choices that are far more entertaining.",
  "I'm on an energy-saving mode that might last a lifetime.",
  "My soul isn't in the mood.",
  "I've already hit my quota for human interaction for the year.",
  "That's a hard no, but thank you for thinking I'm the kind of person who would say yes.",
  "I'm afraid my participation would lower the collective IQ of the group.",
  "Let me get back to you... never. Does never work for you?",
  "I'm actively disengaging from society. It's going well.",
  "I'm currently at my peak of not caring.",
  "I have a chronic condition called 'Not-Feeling-It-itis'.",
  "I'm trying to see if my problems will go away if I ignore them. This is part of that.",
  "That sounds like it would interfere with my carefully planned day of nothing.",
  "I'm sorry, you've reached a number that has been disconnected from all social events.",
  "My motivation and I are in a fight, and I'm not apologizing first.",
  "I'm not sure I have the appropriate wardrobe for that level of effort.",
  "I'd rather be waterboarded with lukewarm soup.",
  "I'm in the process of becoming a hermit, and this is a crucial step.",
  "I'm following my dream of not attending that.",
  "My pet rock and I have other, more stationary plans.",
  "I'm busy. Not 'doing things' busy, just... emotionally busy.",
  "I'm sorry, my schedule is full of things I actually want to do.",
  "I would, but then I'd be there. So, no.",
];